[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements_backend.txt"]

[start]
cmd = "python3 -m uvicorn analyzer:app --host 0.0.0.0 --port $PORT --forwarded-allow-ips='*' --proxy-headers"

